version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 20s
      retries: 10

  github:
    build: .
    links:
      - redis
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      JAVA_TOOL_OPTIONS: -Xms256m -Xmx256m -Duser.home=/tmp -Djava.security.egd=file:/dev/./urandom -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005